/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServiceSlugRouteImport } from './routes/$serviceSlug'
import { Route as CasosDeUsoRouteImport } from './routes/casos-de-uso'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as DiagnosticoRouteImport } from './routes/diagnostico'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SolucoesRouteImport } from './routes/solucoes'
import { Route as CasosDeUsoIndexRouteImport } from './routes/casos-de-uso.index'
import { Route as CasosDeUsoSlugRouteImport } from './routes/casos-de-uso.$slug'
import { Route as InsightsIndexRouteImport } from './routes/insights.index'
import { Route as InsightsSlugRouteImport } from './routes/insights.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceSlugRoute = ServiceSlugRouteImport.update({
  id: '/$serviceSlug',
  path: '/$serviceSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const CasosDeUsoRoute = CasosDeUsoRouteImport.update({
  id: '/casos-de-uso',
  path: '/casos-de-uso',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticoRoute = DiagnosticoRouteImport.update({
  id: '/diagnostico',
  path: '/diagnostico',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SolucoesRoute = SolucoesRouteImport.update({
  id: '/solucoes',
  path: '/solucoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CasosDeUsoIndexRoute = CasosDeUsoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CasosDeUsoRoute,
} as any)
const CasosDeUsoSlugRoute = CasosDeUsoSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CasosDeUsoRoute,
} as any)
const InsightsIndexRoute = InsightsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InsightsRoute,
} as any)
const InsightsSlugRoute = InsightsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => InsightsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$serviceSlug': typeof ServiceSlugRoute
  '/casos-de-uso': typeof CasosDeUsoRouteWithChildren
  '/contato': typeof ContatoRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/insights': typeof InsightsRouteWithChildren
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/solucoes': typeof SolucoesRoute
  '/casos-de-uso/$slug': typeof CasosDeUsoSlugRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/casos-de-uso/': typeof CasosDeUsoIndexRoute
  '/insights/': typeof InsightsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$serviceSlug': typeof ServiceSlugRoute
  '/contato': typeof ContatoRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/solucoes': typeof SolucoesRoute
  '/casos-de-uso/$slug': typeof CasosDeUsoSlugRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/casos-de-uso': typeof CasosDeUsoIndexRoute
  '/insights': typeof InsightsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$serviceSlug': typeof ServiceSlugRoute
  '/casos-de-uso': typeof CasosDeUsoRouteWithChildren
  '/contato': typeof ContatoRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/insights': typeof InsightsRouteWithChildren
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/solucoes': typeof SolucoesRoute
  '/casos-de-uso/$slug': typeof CasosDeUsoSlugRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/casos-de-uso/': typeof CasosDeUsoIndexRoute
  '/insights/': typeof InsightsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$serviceSlug'
    | '/casos-de-uso'
    | '/contato'
    | '/diagnostico'
    | '/insights'
    | '/politica-de-privacidade'
    | '/sitemap.xml'
    | '/sobre'
    | '/solucoes'
    | '/casos-de-uso/$slug'
    | '/insights/$slug'
    | '/casos-de-uso/'
    | '/insights/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$serviceSlug'
    | '/contato'
    | '/diagnostico'
    | '/politica-de-privacidade'
    | '/sitemap.xml'
    | '/sobre'
    | '/solucoes'
    | '/casos-de-uso/$slug'
    | '/insights/$slug'
    | '/casos-de-uso'
    | '/insights'
  id:
    | '__root__'
    | '/'
    | '/$serviceSlug'
    | '/casos-de-uso'
    | '/contato'
    | '/diagnostico'
    | '/insights'
    | '/politica-de-privacidade'
    | '/sitemap.xml'
    | '/sobre'
    | '/solucoes'
    | '/casos-de-uso/$slug'
    | '/insights/$slug'
    | '/casos-de-uso/'
    | '/insights/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ServiceSlugRoute: typeof ServiceSlugRoute
  CasosDeUsoRoute: typeof CasosDeUsoRouteWithChildren
  ContatoRoute: typeof ContatoRoute
  DiagnosticoRoute: typeof DiagnosticoRoute
  InsightsRoute: typeof InsightsRouteWithChildren
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
  SolucoesRoute: typeof SolucoesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$serviceSlug': {
      id: '/$serviceSlug'
      path: '/$serviceSlug'
      fullPath: '/$serviceSlug'
      preLoaderRoute: typeof ServiceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casos-de-uso': {
      id: '/casos-de-uso'
      path: '/casos-de-uso'
      fullPath: '/casos-de-uso'
      preLoaderRoute: typeof CasosDeUsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostico': {
      id: '/diagnostico'
      path: '/diagnostico'
      fullPath: '/diagnostico'
      preLoaderRoute: typeof DiagnosticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes': {
      id: '/solucoes'
      path: '/solucoes'
      fullPath: '/solucoes'
      preLoaderRoute: typeof SolucoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casos-de-uso/': {
      id: '/casos-de-uso/'
      path: '/'
      fullPath: '/casos-de-uso/'
      preLoaderRoute: typeof CasosDeUsoIndexRouteImport
      parentRoute: typeof CasosDeUsoRoute
    }
    '/casos-de-uso/$slug': {
      id: '/casos-de-uso/$slug'
      path: '/$slug'
      fullPath: '/casos-de-uso/$slug'
      preLoaderRoute: typeof CasosDeUsoSlugRouteImport
      parentRoute: typeof CasosDeUsoRoute
    }
    '/insights/': {
      id: '/insights/'
      path: '/'
      fullPath: '/insights/'
      preLoaderRoute: typeof InsightsIndexRouteImport
      parentRoute: typeof InsightsRoute
    }
    '/insights/$slug': {
      id: '/insights/$slug'
      path: '/$slug'
      fullPath: '/insights/$slug'
      preLoaderRoute: typeof InsightsSlugRouteImport
      parentRoute: typeof InsightsRoute
    }
  }
}

interface CasosDeUsoRouteChildren {
  CasosDeUsoSlugRoute: typeof CasosDeUsoSlugRoute
  CasosDeUsoIndexRoute: typeof CasosDeUsoIndexRoute
}

const CasosDeUsoRouteChildren: CasosDeUsoRouteChildren = {
  CasosDeUsoSlugRoute: CasosDeUsoSlugRoute,
  CasosDeUsoIndexRoute: CasosDeUsoIndexRoute,
}

const CasosDeUsoRouteWithChildren = CasosDeUsoRoute._addFileChildren(
  CasosDeUsoRouteChildren,
)

interface InsightsRouteChildren {
  InsightsSlugRoute: typeof InsightsSlugRoute
  InsightsIndexRoute: typeof InsightsIndexRoute
}

const InsightsRouteChildren: InsightsRouteChildren = {
  InsightsSlugRoute: InsightsSlugRoute,
  InsightsIndexRoute: InsightsIndexRoute,
}

const InsightsRouteWithChildren = InsightsRoute._addFileChildren(
  InsightsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ServiceSlugRoute: ServiceSlugRoute,
  CasosDeUsoRoute: CasosDeUsoRouteWithChildren,
  ContatoRoute: ContatoRoute,
  DiagnosticoRoute: DiagnosticoRoute,
  InsightsRoute: InsightsRouteWithChildren,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
  SolucoesRoute: SolucoesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
